package com.battleon

object StarterCollection {
    val cards = listOf(
        CardId.COLLECTOR,
        CardId.WARRIOR,
        CardId.CURSED,
        CardId.HEALER,
        CardId.AGILE,
        CardId.ARAIGNEEGEANTE,
        CardId.BULLDOZER,
        CardId.CHAMANE,
        CardId.DURACUIRE,
        CardId.EPINENOIRE,
        CardId.GRACIEUSEROBUSTE,
        CardId.ROIBAMBOU,
        CardId.SANGUINAIRE,
        CardId.VIOLENT,
        CardId.DANSEUSEMACABRE,
        CardId.DEVINDESTENEBRES,
        CardId.GARDIENDESENFERS,
        CardId.MAITREDESCARNAGES,
        CardId.MAUVAISGENIE,
        CardId.NECROMANCIEN,
        CardId.PORTEURDEGIDEDECHU,
        CardId.PYROMANCIEN,
        CardId.ROIDEMON,
        CardId.SANGPACTE,
        CardId.AMBASSADRICE,
        CardId.BARBAREVIKING,
        CardId.DEVINDELUMIERE,
        CardId.DUC,
        CardId.ENVOUTEUSE,
        CardId.MAGE,
        CardId.REVENDEUR,
        CardId.SENTINELLE,
        CardId.TACTICIEN,
        CardId.THERMOGUERRIER,
        CardId.SQUELETTE_HANTE,
        CardId.SQUELETTE_MALEDICTION,
        CardId.SQUELETTE_FAIBLESSE,
        CardId.ARAIGNEESOLDAT,
        CardId.NOURRICEARAIGNEE,
        CardId.OEUFDARAIGNEE,

    )
}